### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [travs/dev-tools-themes#2]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to change [this usage](https://github.com/travs/dev-tools-themes/blob/7be66ecfb9794bcf1c576972c49dc14a7ea723a0/lib/dev-tools-themes.js) of `require('remote').require('browser-window')` to `require('electron').remote.BrowserWindow`.

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by jerone** [comment]
Deprecation Cop message:

> Use `remote.BrowserWindow` instead of `remote.require("browser-window")`
> 
> ```
> Object.require (C:\Users\jerone\AppData\Local\atom\app-1.12.0-beta2\resources\app.asar\src\electron-shims.js:54:12)
> Object.<anonymous> (C:\Users\jerone\.atom\packages\dev-tools-themes\lib\dev-tools-themes.js:3:28)
> Module.load (module.js:458:32)
> tryModuleLoad (module.js:417:12)
> Function._load (module.js:409:3)
> Package.requireMainModule (C:\Users\jerone\AppData\Local\atom\app-1.12.0-beta2\resources\app.asar\src\package.js:741:27)
> ```
